### `Problem 1`: Write a program that will give you in hand monthly salary after deduction on CTC - HRA(10%), DA(5%), PF(3%) and taxes deduction as below:

> Salary(Lakhs) : Tax(%)

*   Below 5 : 0%
*   5-10 : 10%
*   10-20 : 20%
*   aboove 20 : 30%

In [ ]:
# Write code here
gross_sal = int(input('Enter the salary in CTC: '))
hra = gross_sal*0.1
da = gross_sal*0.05
pf = gross_sal*0.03
taxable_sal = gross_sal - (hra + da + pf)

# tax deduction
if taxable_sal < 500000:
  act_sal =taxable_sal
elif taxable_sal <= 1000000:
  act_sal = taxable_sal-(taxable_sal*0.1)
elif taxable_sal <= 2000000:
  act_sal = taxable_sal-(taxable_sal*0.2)
else:
  act_sal = taxable_sal-(taxable_sal*0.3)

inhand_sal = act_sal /12
print('In-hand salary is: ', inhand_sal)

Enter the salary in CTC: 1200000
In-hand salary is:  73800.0

### `Problem 2`: Write a program that take a user input of three angles and will find out whether it can form a triangle or not.

In [ ]:
# Write code here
a = int(input('Enter the first angle: '))
b = int(input('Enter the second angle: '))
c = int(input('Enter the third angle: '))

if a + b + c == 180:
  print('Yes')
else:
  print('does not form trinagle')

Enter the first angle: 60
Enter the second angle: 50
Enter the third angle: 70
Yes

### `Problem 3`: Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit.

In [ ]:
# Write code here
cp = int(input("Enter the cost price: "))
sp = int(input("Enter the selling price: "))

if cp > sp:
  print('it is a loss')
elif cp < sp:
  print('it is a profit')
else:
  print('it is a tie')

Enter the cost price: 100
Enter the selling price: 120
it is a profit

### `Problem 4`: Write a menu-driven program -
1. cm to ft
2. km to miles
3. USD to INR
4. exit

In [ ]:
# Write code here
def convert():
  print("""
  Welcome,
  Press 1 for : cm to ft
  Press 2 for : km to miles
  Press 3 for : USD to INR
  Press 4 for : exit""")

  value = int(input('Enter: '))
  if value ==1:
    cm = int(input('Enter the value in cm: '))
    ft = cm/30.48
    print('value in foot is: ', ft)

  elif value ==2:
    km = int(input('Enter the value in km: '))
    miles = km *0.621371
    print('value in miles is: ', miles)

  elif value ==3:
    usd = int(input('Enter the value in dollars: '))
    rupee = usd * 82
    print('value in rupee is: ', rupee)

  else:
    print('End')

convert()

  Welcome,
  Press 1 for : cm to ft
  Press 2 for : km to miles
  Press 3 for : USD to INR
  Press 4 for : exit
Enter: 1
Enter the value in cm: 30
value in foot is:  0.984251968503937

### `Problem 5` - Exercise 12: Display Fibonacci series up to 10 terms.

*Note: The Fibonacci Sequence is a series of numbers. The next number is found by adding up the two numbers before it. The first two numbers are 0 and 1. For example, 0, 1, 1, 2, 3, 5, 8, 13, 21. The next number in this series above is 13+21 = 34*

In [ ]:
# Write code here
L = [0,1]
for i in range(0, 8):
  n = L[-1] + L[-2]
  L.append(n)

L

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

### `Problem 6` - Find the factorial of a given number.

Write a program to use the loop to find the factorial of a given number.

The factorial (symbol: `!`) means to multiply all whole numbers from the chosen number down to 1.

For example: calculate the factorial of 5

```bash
5! = 5 × 4 × 3 × 2 × 1 = 120
```

Output:

```bash
120
```

In [ ]:
# Write code here
n = int(input('Enter the number: '))
result = 1
for i in range(1, n+1):

  result = i *result


result

Enter the number: 5

120

### `Problem 7` - Reverse a given integer number.

Example:

`Input:`

```bash
76542
```

`Output:`

```bash
24567
```

In [ ]:
# Write code here
n = int(input('ENter the no.: '))
a = str(n)
L = []
for i in a[-1::-1]:
  L.append(i)

print(''.join(L))

ENter the no.: 76542
24567

### `Problem 8`: Take a user input as integer N. Find out the sum from 1 to N. If any number if divisible by 5, then skip that number. And if the sum is greater than 300, don't need to calculate the sum further more. Print the final result. And don't use for loop to solve this problem.

**Example 1:**

`Input:`

```bash
30
```

`Output:`

```bash
276
```

In [ ]:
# Write code here
n = 30
sum = 0
i = 0

while i < n:
  i = i + 1
  if i % 5 == 0:
    continue
  sum = i + sum
  if sum > 300:
    sum = sum-i
    break

sum

276

### `Problem 9`: Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

In [ ]:
# Write code here
sum = 0
count = 0
while True:
  n = int(input('Enter the no: '))
  if n == 0:
    break

  sum += n
  count += 1

print('sum of numbers is: ', sum)

print('Average is:', sum/count)

Enter the no: 1
Enter the no: 2
Enter the no: 5
Enter the no: 0
sum of numbers is:  8
Average is: 2.6666666666666665

###`Problem 9`: Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

In [ ]:
# Write code here
L = []
for i in range(2000, 3201):
  if i % 7 == 0 and i % 5 != 0:
    L.append(i)
a = str(L)
a

'[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]'

###`Problem 10`: Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a space-separated sequence on a single line.

In [ ]:
# Write code here
L = []
for i in range(1000, 3001):
  flag = True
  curr = i

  while curr > 0:
    last = curr % 10
    if last % 2 != 0:
      flag = False
      break
    curr = curr // 10

  if flag == True:
    L.append(str(i))


print(' '.join(L))

2000 2002 2004 2006 2008 2020 2022 2024 2026 2028 2040 2042 2044 2046 2048 2060 2062 2064 2066 2068 2080 2082 2084 2086 2088 2200 2202 2204 2206 2208 2220 2222 2224 2226 2228 2240 2242 2244 2246 2248 2260 2262 2264 2266 2268 2280 2282 2284 2286 2288 2400 2402 2404 2406 2408 2420 2422 2424 2426 2428 2440 2442 2444 2446 2448 2460 2462 2464 2466 2468 2480 2482 2484 2486 2488 2600 2602 2604 2606 2608 2620 2622 2624 2626 2628 2640 2642 2644 2646 2648 2660 2662 2664 2666 2668 2680 2682 2684 2686 2688 2800 2802 2804 2806 2808 2820 2822 2824 2826 2828 2840 2842 2844 2846 2848 2860 2862 2864 2866 2868 2880 2882 2884 2886 2888

###`Problem 11`: A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps.
The trace of robot movement is shown as the following:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
> The numbers after the direction are steps.

> `!` means robot stop there.

**Please write a program to compute the distance from current position after a sequence of movement and original point.**

*If the distance is a float, then just print the nearest integer.*

Example:

`Input`:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
`Output`:
```
2
```

In [ ]:
# Write code here
pos = [0,0]

while True:
  s = input('Enter: ')
  if s == 'i':
    break
  position = s.split()[0]
  steps = int(s.split()[1])


  if position == 'UP':
    pos[1] = pos[1] + steps
  elif position == 'DOWN':
    pos[1] = pos[1] - steps
  elif position == 'RIGHT':
    pos[0] = pos[0] + steps
  elif position == 'LEFT':
    pos[0] = pos[0] - steps
  else:
    pass

  distance = ((pos[0]**2) + (pos[1]**2))**0.5

print(distance)

Enter: UP 5
Enter: DOWN 5
Enter: LEFT 5
Enter: RIGHT 5
Enter: i
0.0

###`Problem 12`:Write a program to print whether a given number is a prime number or not

In [1]:
# Write code here
num = int(input('Enter the number: '))
flag = True
for i in range(2, num-1):
  if num % i == 0:
    flag = False
    break
if flag == True:
  print('prime num')
else:
  print('not prime')

Enter the number: 7
prime num

###`Problem 13`:Print all the Armstrong numbers in a given range.
Range will be provided by the user<br>
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.

In [ ]:
# Write code here

###`Problem 14`:Calculate the angle between the hour hand and minute hand.

Note: There can be two angles between hands; we need to print a minimum of two. Also, we need to print the floor of the final result angle. For example, if the final angle is 10.61, we need to print 10.

Input:<br>
H = 9 , M = 0<br>
Output:<br>
90<br>
Explanation:<br>
The minimum angle between hour and minute
hand when the time is 9 is 90 degress.

In [ ]:
# Write code here

###`Problem 15`:Given two rectangles, find if the given two rectangles overlap or not. A rectangle is denoted by providing the x and y coordinates of two points: the left top corner and the right bottom corner of the rectangle. Two rectangles sharing a side are considered overlapping. (L1 and R1 are the extreme points of the first rectangle and L2 and R2 are the extreme points of the second rectangle).

Note: It may be assumed that the rectangles are parallel to the coordinate axis.

<img src='https://www.geeksforgeeks.org/wp-content/uploads/rectanglesOverlap.png' width='300' height='200'>

In [ ]:
# Write code here