###`Problem 1:` Combine two lists index-wise(columns wise)

Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

`Given List:`
```
list1 = ["M", "na", "i", "Kh"]
list2 = ["y", "me", "s", "an"]
```

`Output:`
```
[['M','y'], ['na', me'], ['i', 's'], ['Kh', 'an']]
```

In [ ]:
# Write code here
list1 = ["M", "na", "i", "Kh"]
list2 = ["y", "me", "s", "an"]

list3 = list([i,j] for i,j in (zip(list1, list2)))
print(list3)

[['M', 'y'], ['na', 'me'], ['i', 's'], ['Kh', 'an']]

### `Problem 2:` Add new item to list after a specified item
Write a program to add item 7000 after 6000 in the following Python List
```
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
```
`Output:`
```
[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
```

In [ ]:
# Write code here
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
list1

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

###`Problem 3:` Update no of items available

Suppose you are given a list of candy and another list of same size representing no of items of respective candy.

i.e -  
```
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
```

Write a program to show no. of items of each candy type.

`Output:`

```
Jelly Belly-10
Kit Kat-20
Double Bubble-34
Milky Way-74
Three Musketeers-32

```

In [ ]:
# Write code here
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
for (candy, item) in zip(candy_list, no_of_items):
  print(str(candy+'-'+str(item)))

Jelly Belly-10
Kit Kat-20
Double Bubble-34
Milky Way-74
Three Musketeers-32

In [ ]:
[i+'-'+str(j) for i, j in zip(candy_list, no_of_items)]

['Jelly Belly-10',
 'Kit Kat-20',
 'Double Bubble-34',
 'Milky Way-74',
 'Three Musketeers-32']

###`Problem 4:` Running Sum on list
Write a program to print a list after performing running sum on it.

i.e:

`Input:`
```
list1 = [1,2,3,4,5,6]
```
`Output:`
```
[1,3,6,10,15,21]
```

In [ ]:
# Write code here
list1 = [1,2,3,4,5,6]
sum = 0
L = []
for i in list1:
  sum = sum + i
  L.append(sum)

L

[1, 3, 6, 10, 15, 21]

###`Problem 5:` You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.

i.e. Say given list is `[2,4,6,10,1]`
resultant list will be `[22,20,10,23]`.

For 1st element `2` ->> these are greater `(4+6+10)` values and `2` itself so on adding becomes `22`.

For 2nd element `4` ->> greater elements are `(6, 10)` and `4` itself, so on adding `20`

like wise for all other elememts.

`[2,4,6,10,1]`-->`[22,20,16,10,23]`

In [ ]:
# Write code here
# Write code here
L = [2,4,6,10,1]
new_l = []

for i in L:
    k = 0
    for j in L:
        if i <= j:
            k +=  j
    new_l.append(k)

new_l

[22, 20, 16, 10, 23]

###`Problem 6:` Find list of common unique items from two list. and show in increasing order

`Input`

```
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
```

`Output:`
```
[34, 67, 89]
```

In [ ]:
# Write code here
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
L = []
for i in num1:
  if i in num2:
    L.append(i)
sorted(L)

[34, 67, 89]

###`Problem 7:` Sort a list of alphanumeric strings based on product value of numeric character in it. If in any string there is no numeric character take it's product value as 1.

`Input:`
```
['1ac21', '23fg', '456', '098d','1','kls']
```

`Output:`
```
['456', '23fg', '1ac21', '1', 'kls', '098d']

```

In [ ]:
from string import digits
# Write code here
from math import prod

L = ['1ac21', '23fg', '456', '098d','1','kls']

digit = [int(char) for char in L if char.isdigit()]

print(prod(digit) if digits else 1)

456

`Problem 8:` Split String of list on K character.

**Example :**

Input:
```bash
['CampusX is a channel', 'for data-science', 'aspirants.']
```

Output:
```bash
['CampusX', 'is', 'a', 'channel', 'for', 'data-science', 'aspirants.']
```

In [ ]:
# Write code here
L = ['CampusX is a channel', 'for data-science', 'aspirants.']
m = []
for i in L:
  m.extend(i.split())
m

['CampusX', 'is', 'a', 'channel', 'for', 'data-science', 'aspirants.']

### `Problem 9:` Convert Character Matrix to single String using string comprehension.

**Example 1:**

Input:
```bash
[['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
```

Output:
```bash
campux is best channel
```

In [ ]:
# Write code here
L = [['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]

' '.join([''.join(sublist) for sublist in L])

'campux is best channel'

### `Problem 10:` Add Space between Potential Words.

**Example:**

Input:

```bash
['campusxIs', 'bestFor', 'dataScientist']
```

Output:
```bash
['campusx Is', 'best For', 'data Scientist']
```

In [ ]:
# Code here
L = ['campusxIs', 'bestFor', 'dataScientist']
m = []
for i in L:
  for j in i:
    if j.isupper():
      j.split()
  m.append(i)

print(m)

['campusxIs', 'bestFor', 'dataScientist']

### `Problem 11:` Write a program that can perform union operation on 2 lists

**Example:**

Input:

```bash
[1,2,3,4,5,1]
[2,3,5,7,8]
```

Output:
```bash
[1,2,3,4,5,7,8]
```

In [ ]:
# Write code here
a = [1,2,3,4,5,1]
b = [2,3,5,7,8]
c = []
for i in a:
  if i not in c:
    c.append(i)

for i in b:
  if i not in c:
    c.append(i)

print(c)

[1, 2, 3, 4, 5, 7, 8]

### `Problem 12:` Write a program that can find the max number of each row of a matrix

**Example:**

Input:

```bash
[[1,2,3],[4,5,6],[7,8,9]]
```

Output:
```bash
[3,6,9]
```

In [ ]:
# Write code here
L = [[1,2,3],[4,5,6],[7,8,9]]
a = []
for i in L:
  a.append(max(i))

a

[3, 6, 9]

### `Problem 13:` Write a list comprehension to print the following matrix

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [ ]:
# Write code here
a = [[j for j in range(i*3,(i+1)*3)] for i in range(3)]
a

### `Problem 14:` Write a list comprehension that can transpose a given matrix

matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

[1, 4, 7]<br>
[2, 5, 8]<br>
[3, 6, 9]<br>

In [1]:
# Write code here
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]
a = [[row[i] for row in matrix] for i in range(3)]
a

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

### `Problem 15:` Write a list comprehension that can flatten a nested list

Input<br>
matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

Output:<br>
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# Write code here
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]
a = [item for sublist in matrix for item in sublist]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]